### ISSUE TITLE
Error: Cannot find module './uws_linux_x64_127.node' in Node 22

### ISSUE THREAD

**Issue by ppedziwiatr** [kartikk221/hyper-express#266]
node: `v22.2.0`
OS: 
```
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

Error while starting a hyper-express based app:
```
0|app      | Error: Cannot find module './uws_linux_x64_127.node'
0|app      | Require stack:
0|app      | - /home/ao/ao-cu/node_modules/uWebSockets.js/uws.js
0|app      | - /home/ao/ao-cu/node_modules/hyper-express/index.js
0|app      |     at /home/ao/ao-cu/node_modules/uWebSockets.js/uws.js:22:9
0|app      |     at Object.<anonymous> (/home/ao/ao-cu/node_modules/uWebSockets.js/uws.js:24:3)
0|app      |     at Module._compile (node:internal/modules/cjs/loader:1434:14)
0|app      |     at Module._extensions..js (node:internal/modules/cjs/loader:1518:10)
0|app      |     at Module.load (node:internal/modules/cjs/loader:1249:32)
0|app      |     at Module._load (node:internal/modules/cjs/loader:1065:12)
0|app      |     at Module.require (node:internal/modules/cjs/loader:1271:19)
0|app      |     at Hook._require.Module.require (/home/ao/.nvm/versions/node/v22.2.0/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:101:39)
0|app      |     at require (node:internal/modules/helpers:123:16)
0|app      |     at Object.<anonymous> (/home/ao/ao-cu/node_modules/hyper-express/index.js:4:21)
```

**Comment by ppedziwiatr** [comment]
work on `v20.14.0`

**Comment by kartikk221** [comment]
This error means that `uWebsockets.js` (The library used under the hood) does not ship bindings for Node v22 yet.
You can watch or request https://github.com/uNetworking/uWebSockets.js to ship new bindings for Node v22 which `hyper-express` can then increment to update under the hood.
